//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestArea
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILE
    {
        public FILE()
        {
            this.PLAYLISTS = new HashSet<PLAYLIST>();
        }
    
        public string NAME { get; set; }
        public string PATH { get; set; }
        public Nullable<long> DATASTARTPOS { get; set; }
        public Nullable<long> DATALENGTH { get; set; }
    
        public virtual METADATA METADATA { get; set; }
        public virtual ICollection<PLAYLIST> PLAYLISTS { get; set; }
        public virtual METADATA METADATA1 { get; set; }
    }
}
