//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestArea
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARKER
    {
        public string NAME { get; set; }
        public int POS { get; set; }
        public string COMMENT { get; set; }
        public string PLAYLIST { get; set; }
    }
}
