//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestArea
{
    using System;
    using System.Collections.Generic;
    
    public partial class METADATA
    {
        public METADATA()
        {
            this.PLAYLISTS = new HashSet<PLAYLIST>();
        }
    
        public string NAME { get; set; }
        public string TITLE { get; set; }
        public string ARTIST { get; set; }
        public Nullable<int> DURATION { get; set; }
        public string GENRE { get; set; }
        public Nullable<System.DateTime> YEAR { get; set; }
    
        public virtual FILE FILE { get; set; }
        public virtual ICollection<PLAYLIST> PLAYLISTS { get; set; }
        public virtual FILE FILE1 { get; set; }
    }
}
