//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestArea
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GMBAudioLibraryEntities : DbContext
    {
        public GMBAudioLibraryEntities()
            : base("name=GMBAudioLibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FILE> FILES { get; set; }
        public DbSet<MARKER> MARKERS { get; set; }
        public DbSet<METADATA> METADATAs { get; set; }
        public DbSet<PLAYLIST> PLAYLISTS { get; set; }
    }
}
