//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestArea
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYLIST
    {
        public string PLNAME { get; set; }
        public int INDEX { get; set; }
        public string NAME { get; set; }
    
        public virtual FILE FILE { get; set; }
        public virtual METADATA METADATA { get; set; }
    }
}
